server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /usr/share/nginx/html; 
    index index.html index.htm; 
    server_name localhost;
    client_max_body_size 200M;

    # 🛑 BLOQUE PRINCIPAL 
    location / {
        # El alias es necesario para que la reescritura funcione con la raíz de
        alias /usr/share/nginx/html/; 
   
        location ~* \.(jpg|jpeg|gif|png|webp|svg|css|js)$ {
            # Establece el TTL a 1 hora (3600 segundos)
            expires 1h; 
            
            # Sobrescribe Cache-Control para incluir 'must-revalidate'
            add_header Cache-Control "must-revalidate, public, max-age=3600";
            access_log off;
        }
        
        # try_files debe ir DESPUÉS de cualquier location anidado
        try_files $uri $uri/ /index.html;
    }
    

    location ~ /\.ht {
        deny all;
    }
}